import { useOverlay } from '@/store/useOverlay';
import type { Metadata } from 'next';
import { Red_Hat_Text } from 'next/font/google';
import './globals.css';

const inter = Red_Hat_Text({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Product List With Cart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
